### ISSUE TITLE
Energy Sword

### ISSUE THREAD

**Issue by EnashMods** [EnashMods/H3Porting#2]
The sword's blade shader is good, but it's not quite there. It appears as though it is using the shader differently than in h3. 
The scan lines go throughout the blade, when they should be localized to the edge of the blade.

**Comment by Pedro413** [comment]
The plasma waves that go through the sword also have wrong colour, they render black when they should be a light blue. See here https://youtu.be/6WvfmNOM9A0 
The 'cloud effects' I've seen you working on for other weapons also need a shader hack, stems from "objects\weapons\melee\energy_blade\fx\blade_on.effe"
